export const FETCH_AIRCRAFT_PENDING = "FETCH_AIRCRAFT_PENDING";
export const FETCH_AIRCRAFT_SUCCESS = "FETCH_AIRCRAFT_SUCCESS";
export const FETCH_AIRCRAFT_ERROR = "FETCH_AIRCRAFT_ERROR";
export const UPDATE_AIRCRAFT_POSITION = "UPDATE_AIRCRAFT_POSITION";
export const AIRCRAFT_NEW_MISSION = "AIRCRAFT_NEW_MISSION";
export const AIRCRAFT_MISSION_COMPLETE = "AIRCRAFT_MISSION_COMPLETE";
