# Filename: Dockerfile
# Created: Wednesday May 23, 2018
# Modified:
# Author: J. Benjamin Leeds
# License: None
# Purpose: Package gowebclient Golang server

FROM scratch
COPY gowebclient gowebclient
EXPOSE 80
ENTRYPOINT [ "/gowebclient" ]