# Filename: tls-secret.yaml
# Created: Thursday May 24, 2018
# Modified: 
# Author: J. Benjamin Leeds
# License: None

# define TLS secret:
# creates a Kubernetes Secret Object based on the cert and key encoded in base64
# security note: be sure to keep cert and key out of source control, base64 is not encryption

# create secret and push to Kubernetes cluster
# kubectl apply -f secret.yaml

# Kubernetes Secret Documentation: https://kubernetes.io/docs/concepts/configuration/secret/

# Current Issues: 
#   LetsEncrypt/CertBot provides certificates and private keys in .pem format
#   Issue creating Secret Object due to base64 or file incompatibility. 

# Current workaround:
# kubectl imperative command for secret creation: 
# kubectl create secret tls prod-ingress-secret \
# --key ./archive/elevate.airliftnw.org-0001/privkey1.pem \
# --cert ./archive/elevate.airliftnw.org-0001/fullchain1.pem 

# Delete Kubernetes Secret:
# kubectl delete secret prod-ingress-secret

apiVersion: v1
kind: Secret
metadata:
  name: prod-ingress-secret
  namespace: default
type: kubernetes.io/tls  
data:
  fullchain1.pem: base64 encoded cert
  privkey1.pem: base64 encoded key