# .yaml is a superset markup language of JSON
# still structured around key value (key: value) pairs

# helpful commands: 
#   kubectl rollout status deployment/alnw-webclient-nginx-deployment # show deployment status
#   kubectl get deployments # show current deployments
#   kubectl describe service # find ingress IP

# YAML Reference:
# https://www.mirantis.com/blog/introduction-to-yaml-creating-a-kubernetes-deployment/

# Kubernetes API reference:
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#deployment-v1-apps

# Kubernetes NGINX Deployment Reference:
#   https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

apiVersion: v1
kind: Service
metadata:
  name: webclient-loadbalancer-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1 # Kubernetes API Version, Deployments is beta in GCP Kubernetes Engine
kind: Deployment # Recommended over Replication Controller and Pod
metadata: #key
  name: webclient-nginx-deployment #unique key of the deployment instance
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx # "-" signifies a list item
        image: us.gcr.io/airliftnw-uw/webclient
        #image: nginx:1.7.9
        command: [ "/bin/sh", "-c", "cat /etc/nginx/conf.d/default.conf" ]
        imagePullPolicy: Always
        # volumeMounts:
        # - name: config-volume
        #   mountPath: /etc/nginx/conf.d
        # - name: client-volume
        #   mountPath: /usr/share/nginx/html
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: nginx
          