export const FETCH_PEOPLEDETAIL_PENDING = "FETCH_PEOPLEDETAIL_PENDING";
export const FETCH_PEOPLEDETAIL_SUCCESS = "FETCH_PEOPLEDETAIL_SUCCESS";
export const FETCH_PEOPLEDETAIL_ERROR = "FETCH_PEOPLEDETAIL_ERROR";
