export const FETCH_AIRCRAFTDETAIL_PENDING = "FETCH_AIRCRAFTDETAIL_PENDING";
export const FETCH_AIRCRAFTDETAIL_SUCCESS = "FETCH_AIRCRAFTDETAIL_SUCCESS";
export const FETCH_AIRCRAFTDETAIL_ERROR = "FETCH_AIRCRAFTDETAIL_ERROR";
