export const FETCH_AIRCRAFTDETAIL_PENDING = "FETCH_AIRCRAFTDETAIL_PENDING";
export const FETCH_AIRCRAFTDETAIL_SUCCESS = "FETCH_AIRCRAFTDETAIL_SUCCESS";
export const FETCH_AIRCRAFTDETAIL_ERROR = "FETCH_AIRCRAFTDETAIL_ERROR";
export const UPDATE_AIRCRAFTDETAIL_POSITION = "UPDATE_AIRCRAFTDETAIL_POSITION";
export const AIRCRAFTDETAIL_NEW_MISSION = "AIRCRAFTDETAIL_NEW_MISSION";
export const AIRCRAFTDETAIL_MISSION_COMPLETE =
    "AIRCRAFTDETAIL_MISSION_COMPLETE";
