#GOOGLE PUB SUB TEST SCRIPT
$env:GOOGLE_APPLICATION_CREDENTIALS="C:\Users\CR-IO-ADMIN\Downloads\ALNW-PUBSUB-TEST-9b0f2000ec19.json"
$RP = "C:\Users\CR-IO-ADMIN\source\repos\CR-IO_GGL-PubSub-DB\CR-IO_GGL-PubSub-DB\bin\Release" #$(Split-Path $Script:MyInvocation.MyCommand.Path)
Set-Location -Path $RP
$1 = "idyllic-analyst-201102"
$2 = "CRIO-TESTTOPIC"
$3 = [Convert]::ToBase64String(([System.Text.Encoding]::Unicode.GetBytes(("SOME TEST DATA HERE SOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERESOME TEST DATA HERE"))))
$4 = "Key1"
$5 = "Att1"
Get-Date -UFormat %s
Get-Date -UFormat %s
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Start-Process -FilePath "$RP\CR-IO_GGL-PubSub-DB.exe" -ArgumentList "$1 $2 $3 $4 $5"
Get-Date -UFormat %s
pause