export const FETCH_GROUPSDETAIL_PENDING = "FETCH_GROUPSDETAIL_PENDING";
export const FETCH_GROUPSDETAIL_SUCCESS = "FETCH_GROUPSDETAIL_SUCCESS";
export const FETCH_GROUPSDETAIL_ERROR = "FETCH_GROUPSDETAIL_ERROR";
