export const FETCH_MISSIONDETAIL_PENDING = "FETCH_MISSIONDETAIL_PENDING";
export const FETCH_MISSIONDETAIL_SUCCESS = "FETCH_MISSIONDETAIL_SUCCESS";
export const FETCH_MISSIONDETAIL_ERROR = "FETCH_MISSIONDETAIL_ERROR";
