# Filename: secret.yaml
# Created: May 10, 2018
# Modified: 
# Author: J. Benjamin Leeds
# License: None

# define TLS secret:
# creates a Kubernetes Secret Object based on the cert and key encoded in base64
# security note: be sure to keep cert and key out of source control, base64 is not encryption

# Kubernetes Secret Documentation: https://kubernetes.io/docs/concepts/configuration/secret/

# Current Issues: 
#   LetsEncrypt/CertBot provides certificates and private keys in .pem format
#   Issue creating Secret Object due to base64 or file incompatibility. 

# Current workaround:
#   kubectl create secret tls crewjam-test-elevate-airliftnw-org-letsencrypt --key test.elevate.airliftnw.org-privkey1.pem --cert test.elevate.airliftnw.org-fullchain1.pem --save-config
#   run above command in directory where .pem files are stored

apiVersion: v1
kind: Secret
metadata:
  name: crewjam-test-elevate-airliftnw-org-letsencrypt
  namespace: default
type: Opaque
data:
  test.elevate.airliftnw.org-fullchain1.pem: base64 encoded cert
  test.elevate.airliftnw.org-privkey1.pem: base64 encoded key